### PR TITLE
The Logging Update

### PR DESCRIPTION
**Pull request by falukerites**
Work In Progress!

Don't merge yet!

### CODE REVIEW

**Comment by falukerites** [comment]
Fixes #151

**Comment by iSach** [comment]
Thanks a lot for that!
Can I merge now?

**Comment by falukerites** [comment]
Not yet i will finish it soon

**Comment by iSach** [comment]
Alright

**Comment by iSach** [comment]
Any news?

**Comment by kessanro** [comment]
i dont think anything is going to happen

**Pull request closed without merging**
