### PR TITLE
Minecraft 1.18.1 support

### LINKED ISSUE #553: Clearing pathfinders throws exception on Airplane
(this issue was filled out based on messages from Derim on the UC Discord server)
### What steps will reproduce the issue?
1. Run UC on Airplane 1.16.5
2. Use any cosmetic that uses `EntityUtil#clearPathfinders`, such as Explosive Sheep gadget
3. See console error(s)

### What was supposed to happen?
No console error; pathfinders are cleared correctly.
### What happened? 
Console error; pathfinders may not work as expected
### What version of UltraCosmetics are you using?  
2.5.11
### What Spigot version are you using? Paste the output of /version below.  
Airplane 1.16.5 (unknown build)
### What plugins do you have installed? Paste the output of /plugins below.  
unknown; not related to other plugins
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[21:17:33 WARN]: java.lang.IllegalArgumentException: Can not set final gg.airplane.structs.LinkedHashSetArrayList field net.minecraft.server.v1_16_R3.PathfinderGoalSelector.d to java.util.LinkedHashSet
[21:17:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[21:17:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[21:17:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
[21:17:33 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:793)
[21:17:33 WARN]:        at be.isach.ultracosmetics.v1_16_R3.PathfinderUtil.removePathFinders(PathfinderUtil.java:55)
[21:17:33 WARN]:        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:110)
[21:17:33 WARN]:        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:63)
[21:17:33 WARN]:        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:55)
[21:17:33 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.toggleOn(MenuPets.java:166)
[21:17:33 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.toggleOn(MenuPets.java:35)
[21:17:33 WARN]:        at be.isach.ultracosmetics.menu.CosmeticMenu.lambda$open$1(CosmeticMenu.java:183)
[21:17:33 WARN]:        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133)
[21:17:33 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor114.execute(Unknown Source)
[21:17:33 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:17:33 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:17:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:17:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2797)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1330)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1323)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1299)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1143)
[21:17:33 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[21:17:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
### Any additional information that you would like to provide that may be relevant to the issue?
Cause of the issue: Airplane changes the type of field `d` in `PathfinderGoalSelector`, but UC replaces this field with a new LinkedHashSet (the original field type).

Suggested fix: use `clear()` on existing collection instead of replacing it.

### PR DESCRIPTION
**Pull request by datatags**
### What is the purpose of this pull request?
1. **Adds Minecraft 1.18.1 support**
2. Required upgrade to Gradle 7.3.2 (for Java 17, required by MC 1.18)
3. Minor code cleanup; fixes misc. bugs; adds misc. features
4. WorldGuard support! #554

### How do your changes address the purpose?
1. Added and semi-tested v1_18_R1 module
2. Upgraded Gradle wrapper; changed usage of `compile` to `implementation` (may benefit from further optimization)
3. Misc, see changes list.
4. Added two flags, uc-cosmetics and uc-treasurechest. WG API changes substantially between versions 6.2 and 7.0, so subprojects v1_12_R1 and v1_13_R2 host compatibility classes for those.

### Changes
Category as per purpose list is in parenthesis
- [X] (1) Add v1_18_R1 module
- [X] (3) Removed `PathfinderUtil`
- [X] (2) Upgraded Gradle
- [X] (1) Tested mounts
- [X] (1) Tested pets
- [ ] (1) ~~Tested morphs (waiting on LibsDisguises and [ProtocolLib](https://github.com/dmulloy2/ProtocolLib/pull/1446))~~ It's been announced on the LD discord that a working 1.18 build will be a while (i.e. not till 2022) so I'm not gonna worry about it for now
- [X] (1) Make any required changes for 1.18 full release
- [X] (1) Make any required changes for 1.18.1 release
- [X] (3) Adjusted EntityUtil in v1_16_R3 module to fix #553 
- [X] (4) Added WorldGuard support (flags `uc-cosmetics` and `uc-treasurechest`)
- [X] (3) Adjusted morphs to show player name
- [X] (3) Changed Disabled-Commands config option so it blocks commands when any cosmetic is equipped, and added permission check (`ultracosmetics.bypassdisabledcommands`)
- [X] (3) Added a warning if NMS changed without changing NMS revision (by checking `CraftMagicNumbers#getMappingsVersion()`)
- [X] (3) Replaced all references to `ServerVersion.v1_8_R1` with `ServerVersion.earliest()` to prepare for potentially removing v1_8_R1 module
- [X] (3) Replaced many instances of `ServerVersion#compare(ServerVersion)` with a new method, `ServerVersion#isAtLeast(ServerVersion)` for better readability.
- [X] (1) Use existing methods in Brain to remove memories to prevent error when removing villagers
- [X] (3) Add null check on interact listener, apparently a PlayerInteractEvent is triggered when a player logs out while on a pressure plate?
- [X] (3) When looking for players currently opening treasure chests, make sure Bukkit knows about them (`Bukkit.getPlayer(UUID)`) before using as an UltraPlayer. This prevents attempting to make an UltraPlayer from a player NPC.

### CODE REVIEW

**Comment by datatags** [comment]
Gonna go ahead and mark this ready for review, who knows when a 1.18 LD build will be available.

**Comment by datatags** [comment]
In this last commit I removed some modules that bStats showed literally nobody was using. These modules include:
- v1_8_R1
- v1_8_R2
- v1_9_R1
- v1_9_R2
- v1_10_R1
- v1_11_R1
- v1_13_R1
This reduces the jar size by 25% and vastly speeds up both compiling prep and actual compliation.

**Comment by datatags** [comment]
Hey @iSach, thanks for merging this. I've been trying to contact you on Discord if you have some time, I have some questions for you. Thanks!

**Comment by iSach** [comment]
> Hey @iSach, thanks for merging this. I've been trying to contact you on Discord if you have some time, I have some questions for you. Thanks!

Hey sure I apologize for the long delays. I have a very little time to dedicate to my projects, but I'll try to upload at least this update with all your changes. Thanks a lot for your contributions!

**Comment by iSach** [comment]
I tested all the cosmetics.
Only issue I found was: Snowman pet leaves snow on ground.

**Comment by datatags** [comment]
> I tested all the cosmetics. Only issue I found was: Snowman pet leaves snow on ground.

Ok, should I go ahead and fix it or are you working on it?

**Pull request merged**
