### PR TITLE
1.10

### PR DESCRIPTION
**Pull request by galaxyoyo**
Added 1.10 compatibility.
However, didn't looked at EntityLiving.be and EntityLiving.aB replacement.

### CODE REVIEW

**Comment by galaxyoyo** [comment]
There was a problem with LibsDisguises, the plugin wasn't up-to-date, so it was unpossible to disable the third-person-view. Don't tested for 1.8.8 and 1.9.X, but the update works for 1.10. (I'll test now)

**Comment by galaxyoyo** [comment]
OK, I tested all versions and all is working. Be careful: if you're running 1.8.8 or 1.9.X versions with the latest versions of LibsDisguises and ProtocolLib, client will crash when enabling third-person-view.

**Comment by galaxyoyo** [comment]
Some cosmetics were disabled for 1_9_R1. There are now also disabled for 1_9_R2 and 1_10_R1.

**Comment by 112madgamer** [comment]
Awesome update however treasure chests are broken to.

**Pull request closed without merging**
