### PR TITLE
Add reload command

### PR DESCRIPTION
**Pull request by montlikadani**
Its purpose is to reload at least the configuration so that it does not always have to stop and restart the server.

Shorten, adds the `/uc reload` command to reload the configuration (**only config.yml**).

#### Changes
- [x] Add reload command.

### CODE REVIEW

**Comment by iSach** [comment]
Thanks for your pull request.
However, just reloading the file configuration can have a lot of issues with the players currently using the gadgets, etc. For example, the chest in the inventory can be changed:
- Item
- Slot
etc
So if you reload and that in the config it's a different GUI item, it won't work.
Another example: if a gadget is disabled in config people who activated before the reload will still be able to use it (or it will just bug, can't say just like that) so it creates tons of things to deal with, mostly everything dealt with in the onEnable/onDisable method that needs to be done on the reload command.

It is a mess and that's why there is no command yet, it needs to adjust to everything to avoid any conflict. Just a call of the loadConfiguration is not enough to ensure a correct config reload.

Feel free to edit it if you have the time to spend on that feature, would be greatly appreciated.

**Comment by montlikadani** [comment]
I did that when the operator reloads the plugin, just remove the menu item from the inventory and return it to it.

**Comment by montlikadani** [comment]
sorry for the a lots of commit fails

**Comment by montlikadani** [comment]
This is not just a simple configuration update, it reloads the configuration and removes the item from the player inventory, but immediately returns it as the user may have edited something on the name of the cosmetics.
If a player has an ammo, cosmetics or something and the player leave from the server, it re-connects to the latest when the server owner has edited something.

That's right? I saw that in the code.

**Comment by montlikadani** [comment]
It seems, this sub-command argument not yet added. Why closed when simply mention me to re-work the code and implement code to this sub-command will add to the plugin?

**Comment by iSach** [comment]
@montlikadani Hello, sorry for not adding a comment.

This feature has been dropped from plans for the reasons told by RadBuilder above.
When everything is fully working on UltraCosmetics for 1.8 to 1.14.4, a lot of refactor is going to happen to clean and reorganize several parts of the code. Until then, a reload command is not something we plan to do.

**Pull request closed without merging**
