### PR TITLE
A mount and a few fixes

### PR DESCRIPTION
**Pull request by JHXSMatthew**
1. Copy your work and mess them into one mount "flying boat", I cannot think any good english name for it . You may change it to something much more interesting.
  - it's a boat could flying around like EnderDragon
  - Right click or left click will spawn an TNT , when the TNT reaches the ground, it will explode. Cooldown 10 seconds without any message or actionbar notification (not like gadgets).
  - Uhm... What's more ?

2. Fix TreasureChest class's import stuff.

Cheers!

### CODE REVIEW

**Comment by iSach** [comment]
Hey, once more thanks for your contributions again.

I can't work a lot these days because of school.

For the boat, Flying Ship could be cool, as it drops bombs.

What was bugging with treasure chests?

**Comment by JHXSMatthew** [comment]
For treasure chests, I forgot to import the class "fixedMetaValue" in last pull request.
This pull request just patch this .

I would create new pull request with name changing soon. 
Cheers!

**Comment by iSach** [comment]
Okay, thanks!

**Comment by JHXSMatthew** [comment]
It looks like every file I modify a bit has to be "re-written" (- all original lines and + again).
I have no ideas why this happens.
What's encoding do you use for each file , GBK or utf-8 or something else?

**Comment by JHXSMatthew** [comment]
for commit ed32f6c
just fix #39  by removing the import "bungee's stuff".

**Comment by iSach** [comment]
Thanks again.

I use UTF-8. I'm gonna work on it today.

I must find the reason of armor stand pets' name tags not disappearing. I'm the only person not getting this issue.

Then all the known bugs should be fixed. I will also do some testings.

**Pull request merged**
