### PR TITLE
Some silly stuff when spigot goes down shit goes down..

### PR DESCRIPTION
**Pull request by acecheese**

### CODE REVIEW

**Comment by acecheese** [comment]
Can I suggest maven?

**Comment by iSach** [comment]
I'm not familiar with maven :/ and I didn't really found a good tutorial about setting up with a Jenkins etc

**Comment by acecheese** [comment]
Ah okay. Maybe learn, it would sure help when we're trying to build it ourselves!

**Comment by iSach** [comment]
Okay, would you have a good tutorial about it? :)

**Comment by acecheese** [comment]
I'll make one and throw it on youtube tomorrow for you. :) Also I think the depend for LibsDesguises in plugin.yml is incorrect as Lis.... (can't sell.)

**Comment by iSach** [comment]
Okay thanks :D yes it's fixed I must commit

**Comment by acecheese** [comment]
Okay, and might pay off to test the code I wrote.. It was freehand.

**Comment by iSach** [comment]
Thanks for it! It's actually 2am almost here in be I'm not on my computer so I cant test. :/

**Comment by acecheese** [comment]
Ah okay, I'm trying getting all teh depends. I'll fix it if not. :)

**Pull request merged**
